<?php
require('../SinaStorageService.php');
//require_once('../examples/conf.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-19 at 16:45:15.
 */
class SinaStorageServiceTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SinaStorageService
     */
    protected $object;
    protected $bafine;

    public static function setUpBeforeClass()
    {

    }

    public static function tearDownAfterClass()
    {
        // code...
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $conf = $this->getConf();
        $this->object = SinaStorageService::getInstance($conf['project'],
                $conf['accesskey'], $conf['secretkey']);
        $this->object->purgeParams();
        $this->object->purgeReq();
        $this->object->setAuth(true);
        $this->object->setCURLOPTs(array(CURLOPT_VERBOSE=>1));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function getConf()
    {
        $conf = array('project'=>'sandbox', 'accesskey'=>'SYS0000000000SANDBOX',
                 'secretkey'=>'1111111111111111111111111111111111111111');
        return $conf;
    }

    /**
     * @covers SinaStorageService::getInstance
     * @group getInstance
     */
    public function testGetInstance()
    {
        //$o = SinaStorageService::getInstance($project, $accesskey, $secretkey);
        //var_dump($this->object);
        print_r($this->object);
    }

    public function getHttpCode($result)
    {
        $statLine = explode( " ", $result,4);
        $httpCode = $statLine[1];

        return $httpCode;
    }

    /**
     * @covers SinaStorageService::uploadFile
     * @group uploadFile
     * @dataProvider uploadFileData
     */
    public function testUploadFile($localfile, $expected)
    {
        $httpCode = $this->upSingleFile($localfile);

        $this->assertEquals( $expected, $httpCode);
    }

    public function uploadFileData()
    {
        //$allFile = $this->recurseFolder("file4UploadTest");

        return array(
            array( 'file4UploadTest/pas.txt', 200),
            array( 'file4UploadTest/afine.txt', 200)
        );
    }

    //public function upSingleFile($localfile, $change = false)
    public function upSingleFile($localfile)
    {
        $fileType = mime_content_type( $localfile );
        $fileLength = filesize($localfile);
        $fileName = $localfile;
        $fileContent = "";

        $file_handle = fopen( $localfile , "r");
        while (!feof($file_handle)) {
            $fileContent = $fileContent.fread($file_handle,513);
        }
        fclose($file_handle);

        $file_sha1 = sha1($fileContent);
        $this->object->uploadFile("$fileName",$fileContent, $fileLength, $fileType, $result);
        $httpCode = $this->getHttpCode($result);

        return $httpCode;
    }

    public function recurseFolder($directory)
    {
        $allFile = array();
        if( substr($directory,-1,1) != "/" ){
            $directory = "$directory/";
        }

        if( is_file( $directory )) {
            throw new exception("Argument of recurseFolder() should be a string specifying a path");
        }else{
            $mydir=dir($directory);
            while( $file=$mydir->read()){
                if (($file!=".") AND ($file!="..") And ($file!= ".svn" ) And ($file!= ".git" )) {
                    if (!is_file($directory.$file)) {
                        echo $directory.$file." is not a file.\n";
                        continue;
                    }
                    array_push($allFile, "$directory$file");
                }
            }
            $mydir->close();
        }
        return $allFile;
    }

    /**
     * @covers SinaStorageService::uploadFileRelax
     * @group uploadFileRelax
     * @dataProvider uploadFileRelaxData
     */
    public function testUploadFileRelax($localfile, $expected)
    {
        $this->object->setCURLOPTs(array(CURLOPT_VERBOSE=>0));
        $httpCode = $this->upSingleFile($localfile);

        if ($httpCode != 200) {
            echo "fail to upload $localfile";
        }

        $nameRelax = $localfile."Relax";
        $fileContent = "";
        $file_handle = fopen( $localfile , "r");
        while (!feof($file_handle)) {
            $fileContent = $fileContent.fread($file_handle,513);
        }
        fclose($file_handle);

        if ( $expected != 200) {
            $fileContent = "AddTimeInTheEnd--".date("U");
            echo "\n\n".$fileContent."\n\n";
        }

        $file_sha1 = sha1($fileContent);
        $fileLength = strlen($fileContent);

        $this->object->setCURLOPTs(array(CURLOPT_VERBOSE=>1));
        $this->object->uploadFileRelax("$nameRelax",$file_sha1, $fileLength, $result);
        $httpCodeRelax = $this->getHttpCode($result);

        $this->assertEquals( $expected, $httpCodeRelax);

    }

    public function uploadFileRelaxData()
    {
        return array(
            array( 'file4UploadTest/pas.txt', 200),
            array( 'file4UploadTest/afine.txt', 200),
            array( 'file4UploadTest/afine.txt', 400)
        );
    }

    /**
     * @covers SinaStorageService::copyFile
     * @group copyFile
     * @dataProvider copyFileData
     */
    public function testCopyFile($src,$expected)
    {
        $dest = "copied/".array_pop(explode("/",$src,2));
        $this->object->copyFile($dest, $src, $result);
        $httpCode = $this->getHttpCode($result);
        $this->assertEquals($expected, $httpCode);
    }

    public function copyFileData()
    {
        return array(
            array( 'file4UploadTest/pas.txt', 200),
            array( 'file4UploadTest/afine.txt', 200)
        );
    }
    /**
     * @covers SinaStorageService::copyFileBetweenProject
     * @group copyFileBetweenProject
     */
    public function testCopyFileBetweenProject()
    {

    }

    public function copyFileBetweenProjectData()
    {
        return array(
            array( 'file4UploadTest/pas.txt', 200),
            array( 'file4UploadTest/afine.txt', 200)
        );
    }
    /**
     * @covers SinaStorageService::getFile
     * @group getFile
     * @dataProvider getFileData
     */
    public function testGetFile( $filename, $ip, $expected)
    {
        $this->object->setCURLOPTs(array(CURLOPT_HEADER=>1));
        if ( $ip ) {
            $this->object->setExtra("?ip=$ip");
        }

        $this->object->getFile( $filename, $result );
        $httpCode = $this->getHttpCode($result);
        $this->assertEquals( $expected, $httpCode);
    }

    public function getFileData()
    {
        $friend = "/file_uploaded/birth.txt";
        return array(
            array( $friend, '', 200),
            //array( '/file_uploaded/birth.txt', '', 200),
            array( '/file_uploaded/nnn3.txt', '', 200),
            array( 'foo/bar/1.html', '219.142.118.237', 200),
            array( 'foo/bar/1.html', '229.152.128.247', 403),
            array( 'nonexistfile.html', '', 404),
            array( 'foo/bar/1.html', '', 200)
       );
    }

    public function basicData()
    {
        return array(
            array( '/file_uploaded/birth.txt', 200),
            array( '/file_uploaded/nnn3.txt', 200),
            array( 'foo/bar/1.html', 200),
            array( 'nonexistfile.html', 404),
            array( 'foo/bar/1.html', 200)
       );
    }

    /**
     * @covers SinaStorageService::getFileUrl
     * @group getFileUrl
     * @dataProvider getFileUrlData
     */
    public function testGetFileUrl($file, $ip, $expected)
    {
        if ( $ip ) {
            $this->object->setExtra("?ip=$ip");
        }

        $this->object->getFileUrl($file, $result);

        $c = curl_init();
        curl_setopt($c, CURLOPT_URL, $result);
        curl_setopt($c, CURLOPT_CUSTOMREQUEST, "GET");
        curl_setopt($c, CURLOPT_HEADER, 1);
        curl_setopt($c, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($c, CURLOPT_TIMEOUT, 3);

        $c_result = curl_exec($c);
        $c_info = curl_getinfo($c);
        curl_close($c);

        $this->assertEquals($expected, $c_info['http_code']);
    }

    public function getFileUrlData()
    {
        return array(
            array("foo/bar/1.html", "", 200),
            array("foo/bar/1.html", "219.142.118.237", 200),
            array("foo/bar/1.html", "229.152.128.247", 403),
            array("nonexistfile.html", "", 404),
            array("foo/bar/1.html", "", 200)
        );
    }

    /**
     * @covers SinaStorageService::deleteFile
     * @group deleteFile
     * @dataProvider deleteFileData
     */
    public function testDeleteFile( $file, $expected)
    {
        $this->object->setCURLOPTs(array(CURLOPT_HEADER=>1));
        $this->object->deleteFile( $file, $result);
        $httpCode = $this->getHttpCode($result);

        $this->assertEquals( $expected, $httpCode);
    }

    public function deleteFileData()
    {
        return array(
            array( 'file4UploadTest/pas.txt', 204),
            array( 'file4UploadTest/afine.txt', 204)
        );
    }

    /**
     * @covers SinaStorageService::getMeta
     * @group getMeta
     * @dataProvider basicData
     */
    public function testGetMeta($file, $expected)
    {
        $this->object->setCURLOPTs(array(CURLOPT_HEADER=>1));
        $this->object->getMeta($file,$result);
        $httpCode = $this->getHttpCode($result);
        $this->assertEquals($expected,$httpCode);
    }

    /**
     * @covers SinaStorageService::updateMeta
     * @group updateMeta
     * @dataProvider basicData
     */
    public function testUpdateMeta($file,$expected)
    {
        $timeNow = date("U");
        $this->object->setCURLOPTs(array(CURLOPT_HEADER=>1));
        $this->object->setRequestHeaders(array("x-sina-info-int"=>$timeNow,"x-sina-info"=>"test_$file"));
        $this->object->updateMeta($file, $result);
        $httpCode = $this->getHttpCode($result);

        $this->assertEquals($expected, $httpCode);
    }

    /**
     * @covers SinaStorageService::getFileList
     * @group getFileList
     */
    public function testGetFileList()
    {
        $this->object->setCURLOPTs(array(CURLOPT_HEADER=>1));
        $this->object->getFileList($result);
        $httpCode = $this->getHttpCode($result);
        $this->assertEquals(200,$httpCode);
    }

    /**
     * @covers SinaStorageService::listFiles
     * @group listFiles
     * @dataProvider listFilesData
     */
    public function testListFiles($marker, $pageeach)
    {
        /**
         * $this->object->setCURLOPTs(array(CURLOPT_HEADER=>1));
         * listFiles() function return a json-decoded value,
               ignoring whether CURLOPT_HEADER is set,so cannot receive
               the respond header.
         */
        $result = $this->object->listFiles($marker, $pageeach, "");

        $this->assertEquals($marker, $result["Marker"]);
        $this->assertGreaterThan($marker, $result["Contents"][0]["Name"]);
        $this->assertEquals($pageeach, $result["ContentsQuantity"]);
    }

    public function listFilesData()
    {
        return array(
            array( 'foo/bar/1.html', 10, 200),
            array( 'file4UploadTest/afine.txt', 5, 200)
        );
    }
    /**
     * @covers SinaStorageService::setAuth
     * @group setAuth
     */
    public function testSetAuth()
    {
        $this->object->setAuth(false);
        $this->object->getFileUrl("foo/bar/1.html",$result);
        $uri = explode("?",$result,2);
        $this->assertEmpty($uri[1],"setAuth does not work.");

        $this->object->setAuth(true);
        $this->object->getFileUrl("foo/bar/1.html",$result);
        $uri = explode("?",$result,2);
        $this->assertNotEmpty($uri[1],"setAuth does not work.");
    }

    /**
     * @covers SinaStorageService::setExpires
     * @group setExpires
     */
    public function testSetExpires()
    {
        $this->object->setAuth(false);
        $this->object->getFileUrl("foo/bar/1.html",$result);

        $this->object->setAuth(true);
        $this->object->setExpires(121);
        $this->object->getFileUrl("foo/bar/1.html",$result);

        $urlQueryStrArr = explode("&",$result);
        array_splice($urlQueryStrArr,0,1);

        $urlQueryStr = array();
        foreach ($urlQueryStrArr as $key) {
            $temp = explode("=", $key, 2);
            $urlQueryStr[$temp[0]] = $temp[1];
        }

        $this->assertArrayHasKey("ssig", $urlQueryStr, "setExpires fail.");
        $this->assertArrayHasKey("KID", $urlQueryStr, "setExpires fail.");
        $this->assertArrayHasKey("Expires", $urlQueryStr, "setExpires fail.");
    }

    /**
     * @covers SinaStorageService::setExtra
     * @group setExtra
     * @dataProvider setExtraData
     */
    public function testSetExtra($extra)
    {
        $this->object->setExtra($extra);
        $this->object->getFileUrl("foo/bar/1.html",$result);

        $urlParts = explode("?",$result, 2);
        $urlExtra = "?".substr($urlParts[1],0,strlen($extra)-1);

        $this->assertEquals($extra, $urlExtra);
    }

    public function setExtraData()
    {
        return array(
            array("?meta"),
            array("?acl"),
            array("?logging"),
            array("?relax"),
            array("?location")
        );
    }

    /**
     * @covers SinaStorageService::setQueryStrings
     * @group setQueryStrings
     * @dataProvider setQueryStringsData
     */
    public function testSetQueryStrings($queryStr)
    {
        $this->object->setQueryStrings($queryStr);
        $this->object->getFileUrl("foo/bar/1.html",$result);

        $urlQueryStrArr = explode("&",$result);
        array_splice($urlQueryStrArr,0,1);

        $urlQueryStr = array();
        foreach ($urlQueryStrArr as $key) {
            $temp = explode("=", $key, 2);
            $urlQueryStr[$temp[0]] = $temp[1];
        }

        $intersection = array_intersect($urlQueryStr,$queryStr);
        $this->assertEquals($queryStr, $intersection);
    }

    public function setQueryStringsData()
    {
        $qs1 = array(
            'formatter' => 'json',
            'marker' => 'makerVal',
            'max-keys' => 10
        );
        $qs2 = array(
            'doodle' => 'diagonal',
            'orientation' => 'heaven'
        );

        return array(
            array($qs1),
            array($qs2)
        );
    }

    /**
     * @covers SinaStorageService::setRequestHeaders
     * @todo   Implement testSetRequestHeaders().
     */
    public function testSetRequestHeaders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SinaStorageService::setCURLOPTs
     * @group setCURLOPTs
     * @dataProvider setCURLOPTsData
     */
    public function testSetCURLOPTs($curlOpt)
    {
        $this->object->setCURLOPTs($curlOpt);
        $result = $this->object->getCURLOPTs();

        if (!array_key_exists(CURLOPT_VERBOSE,$curlOpt)) {
            unset($result[CURLOPT_VERBOSE]);
        }
        $this->assertEquals($curlOpt, $result);
    }

    public function setCURLOPTsData()
    {
        $curlOpt1 = array(
            CURLOPT_HEADER=>1,
            CURLOPT_CONNECTTIMEOUT=>10,
            CURLOPT_RETURNTRANSFER=>1
        );
        $curlOpt2 = array(
            CURLOPT_VERBOSE=>True,
            CURLOPT_TIMEOUT=>60
        );

        return array(
            array($curlOpt1),
            array($curlOpt2)
        );
    }
    /**
     * @covers SinaStorageService::setTimeout
     * @todo   Implement testSetTimeout().
     */
    public function testSetTimeout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SinaStorageService::setDomain
     * @group setDomain
     */
    public function testSetDomain()
    {
        $this->object->getFileUrl("foo/bar/1.html",$result);
        $this->assertStringStartsWith("http://sinastorage.com/", $result);

        $this->object->setDomain("http://IJustChangeTheDomain.com/");

        $this->object->getFileUrl("foo/bar/1.html",$result);
        $this->assertStringStartsWith("http://IJustChangeTheDomain.com/", $result);
    }

    /**
     * @covers SinaStorageService::getCURLOPTs
     * @group getCURLOPTs
     * @dataProvider getCURLOPTsData
     */
    public function testGetCURLOPTs($curlOpt)
    {
        $this->object->setCURLOPTs($curlOpt);
        $result = $this->object->getCURLOPTs();

        if (!array_key_exists(CURLOPT_VERBOSE,$curlOpt)) {
            unset($result[CURLOPT_VERBOSE]);
        }
        $this->assertEquals($curlOpt, $result);
    }

    public function getCURLOPTsData()
    {
        $curlOpt1 = array(
            CURLOPT_HEADER=>1,
            CURLOPT_CONNECTTIMEOUT=>10,
            CURLOPT_RETURNTRANSFER=>1
        );
        $curlOpt2 = array(
            CURLOPT_VERBOSE=>True,
            CURLOPT_TIMEOUT=>60
        );

        return array(
            array($curlOpt1),
            array($curlOpt2)
        );
    }
    /**
     * @covers SinaStorageService::purgeParams
     * @group purgeParams
     * @dataProvider purgeParamsData
     */
    public function testPurgeParams($queryStr, $curlOpt, $requestHeader)
    {
        $this->object->setExpires(123);
        $this->object->setExtra("?acl");
        $this->object->setQueryStrings($queryStr);
        $this->object->setCURLOPTs($curlOpt);
        $this->object->setRequestHeaders($requestHeader);

        $this->object->getFileUrl("foo/bar/1.html",$result);
        $uri = explode("?",$result,2);
        $getCurlOpt = $this->object->getCURLOPTs();
        $this->assertNotEmpty($uri[1],"Fail to setExtra and setQueryStrings.");
        $this->assertNotEmpty($getCurlOpt,"Fail to setCURLOPTs.");

        $this->object->purgeParams();

        $this->object->getFileUrl("foo/bar/1.html",$result);
        $uri = explode("?",$result,2);
        $getCurlOpt = $this->object->getCURLOPTs();
        $this->assertEmpty($uri[1],"Fail to purgeParams.");
        $this->assertEmpty($getCurlOpt,"Fail to purgeParams.");
    }

    public function purgeParamsData()
    {
        $queryStr = array(
            'formatter' => 'json',
            'marker' => 'makerVal',
            'max-keys' => 10
        );
        $curlOpt = array(
            CURLOPT_HEADER=>1,
            CURLOPT_CONNECTTIMEOUT=>10,
            CURLOPT_RETURNTRANSFER=>1
        );
        $requestHeader = array(
            "Content-Type" => "text/plain",
            "Content-Length" => "11",
            "Content-MD5" => "XrY7u+Ae7tCTyyK7j1rNww=="
        );
        return array(
            array($queryStr, $curlOpt, $requestHeader)
        );
    }

    /**
     * @covers SinaStorageService::purgeReq
     * @group purgeReq
     * @dataProvider purgeReqData
     */
    public function testPurgeReq($queryStr, $curlOpt, $requestHeader)
    {
        $this->object->setExtra("?acl");
        $this->object->setQueryStrings($queryStr);
        $this->object->setCURLOPTs($curlOpt);
        $this->object->setRequestHeaders($requestHeader);

        $this->object->getFileUrl("foo/bar/1.html",$result);
        $uri = explode("?",$result,2);
        $getCurlOpt = $this->object->getCURLOPTs();
        $this->assertNotEmpty($uri[1],"Fail to setExtra and setQueryStrings.");
        $this->assertNotEmpty($getCurlOpt,"Fail to setCURLOPTs.");

        $this->object->purgeReq();
        $this->object->setAuth(false);

        $this->object->getFileUrl("foo/bar/1.html",$result);
        $uri = explode("?",$result,2);
        $getCurlOpt = $this->object->getCURLOPTs();
        $this->assertEmpty($uri[1],"Fail to purgeReq.");
        $this->assertEmpty($getCurlOpt,"Fail to purgeReq.");
    }

    public function purgeReqData()
    {
        $queryStr = array(
            'formatter' => 'json',
            'marker' => 'makerVal',
            'max-keys' => 10
        );
        $curlOpt = array(
            CURLOPT_HEADER=>1,
            CURLOPT_CONNECTTIMEOUT=>10,
            CURLOPT_RETURNTRANSFER=>1
        );
        $requestHeader = array(
            "Content-Type" => "text/plain",
            "Content-Length" => "11",
            "Content-MD5" => "XrY7u+Ae7tCTyyK7j1rNww=="
        );
        return array(
            array($queryStr, $curlOpt, $requestHeader)
        );
    }
}
